# -*- coding: utf-8 -*-
"""Qrcode generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i9ewiQzvyaXrg7kom1rKCoabejeIynNY
"""

pip install pypng

pip install pyqrcode

import pyqrcode
import png
from pyqrcode import QRCode
s="https://www.instagram.com/_manu_v/"
url=pyqrcode.create(s)
url.png('myqr.png',scale=6)